'use strict';
// The changelog on Help → Changelog: newest first, each line tagged with the short hash of the
// commit that made the change (a link to it on GitHub). A commit can't name its own hash, so add the
// line in a follow-up commit that cites the change's commit.
const CHANGELOG_REPO = 'https://github.com/Mikanwolfe/Artillery3/commit/';
const CHANGELOG = [
  ['5187307', 'CPUs actually buy air defence now: anti-air when their rivals have planes (or drones are about), point defence against rockets, from up to half their money, and they trade up as the rounds go on.'],
  ['fb05bb5', 'AA mounts show on the girls’ backs: flak barrels that swing onto their targets and kick, rocket boxes, radomes, pods and lenses. November’s starting flak is much stronger (about two of a starter squad’s three planes a pass), and all anti-air focuses on the plane with the least left. AA mounts are bought, not mounted, in the shop.'],
  ['438d74a', 'Hits on planes, and point defence’s hits on rockets, show the same damage popups as any other hit (with AA, POINT DEFENCE or ARMOUR tags) instead of plain numbers and percentages.'],
  ['06f8fe9', 'The skyrail train looks like a Melbourne Metro train now: silver stainless with a blue band, blue doors edged in yellow and blue cab fronts.'],
  ['1201391', 'A thinner health and armour bar. CPUs favour their own girl’s line when buying and choosing guns (her makers, and her starter’s kind), and only Ikaros’s CPU likes lasers, since CPUs aim them badly.'],
  ['b18ec08', 'Fixed a crash when using a repair kit. Starting guns and mounts can be sold (for ¢250 scrap) to free their slot, and a bought mount replaces a girl’s own one, Zuihou’s Type 96 included. Torpedo jets get two passes instead of one.'],
  ['07ca353', 'FPV kamikazes come in high and spend their first cycle flying in from the edge without attacking, so they can no longer appear next to you at the map edge and blow you up at once. After that they get over their target and dive onto it from the sky.'],
  ['ac3cfcf', 'One bar under each girl: health, with armour laid over it (armour goes first and uncovers the health under it), and one number, armour and health together. Every heal (repair kits, crates, the field workshop) goes to health first, then armour. Fortress planes show their armour the same way.'],
  ['6bd0dca', 'Point defence engages every rocket and bomb in range and each hit takes a share of its damage off (random, and less off heavy warheads); one left with little is shot down. Light rockets rarely land against good point defence, heavy ones get through damaged and smoking. All seeker rockets see further and turn harder. Anti-air guns now burst as flak.'],
  ['f2419de', 'Codex: an AA filter lists every air-defence mount (hers first) with a side-by-side table, and you can test the chosen one on the range: a squad flies a low or high pass over you without attacking (see the damage your mount does and how many it would down), or a rocket salvo comes in (see how many it stops). A Blast radius weight slider sets how much a bigger blast counts in a gun’s worth and redraws its value and the chart.'],
  ['c012c15', 'Every girl starts with an AA mount of her own (Ikaros weakest, then Innocentia, Alban Eiler, G.W. Tiger, Object 15X, Zuihou, November); a bought mount replaces it. November’s Gatekeeper is now the Defensive Suite: two slots, point defence and flak from the start. Anti-air bursts that miss still graze. Planes can strike MAIA. Object 15X’s designator now homes her rounds onto the mark. NXi guns with tight blasts hit about 12% harder. Rounds have a dark outline. Walking on a bridge no longer rams the trees below.'],
  ['fc7ba51', 'Planes strike the turn you call them: each dot sends a squad (or redirects one already out) and it attacks there and then; between dots it hovers over its zone, a target. No more waiting a turn, the Kidō Butai included. A squad whose girl is destroyed flies off.'],
  ['88c4b7c', 'Planes swing through turns on a damped spring instead of pivoting. A squad’s label is its badge and a pip a pass left. Badges say what a plane carries (Cb bombs, Ct torpedoes, Cf fighters, Cr rockets; flak is now Ck). CPUs killed by planes buy anti-air first. Sengoku weapons are SI, the planes have VTuber-homage nicknames, and the final tier is Parallel Night.'],
  ['13296ec', 'Kidō Butai is one 21-plane squad: it strikes on each of her turns until its loadouts run out, each dot redirects the whole fleet, and the carriers won’t launch again until it is gone. The sea is far out past a proper coastline now (no more hills clipping into it).'],
  ['d2f5c27', 'Plane squads work like autoloader rounds: each dot of a turn takes the next squad (launch, or redirect one already out), one squad per strike zone, pips on the rack. Squads only hit what is inside their zone. Fixed extra squads in the Codex range.'],
  ['d2f5c27', 'Planes fly for real: speed, thrust, gravity and a turn radius, so bombers climb, tip over into the dive and loop back up to hover. Every plane shows its health, tougher with rarity; plane bombs and rockets actually steer now.'],
  ['d2f5c27', "New Sengoku 'Fortissimo' Flying Fortress: level bombers that walk a stick of bombs across a wide zone, with armour that takes a whole hit (the Taufaun has some too)."],
  ['cc86f17', 'Plane squads are ammo: one early, up to four late. A shot sends a squad, or with none in reserve redirects one already out to the new dot. Lost or spent squads rearm and come back.'],
  ['32b1e58', 'Planes hunt like drones: a squad locks onto the nearest rival and strikes on each of your turns until its loadout is spent (bombers three, torpedo jets one, fighters six), then flies home to rearm. Zuihou gets a deck gun for meanwhile.'],
  ['0e28912', 'Planes fly smooth curves and bank as they turn; all jets but the starter. Each type waits on its own approach line and attacks down it, dive bombers steep and fast enough for a kinetic bonus.'],
  ['0e28912', 'Launching no longer holds up the turn: the squad flies out while play goes on.'],
  ['0e28912', 'The Taufaun is one armoured jet with one enormous bomb. Planes are named after visual novels.'],
  ['0e28912', 'A squad whose girl is destroyed stays on and still strikes.'],
  ['0e28912', 'Health, name and a short gun name now sit under each girl; aim dots and the marker have white rims.'],
  ['0e28912', 'The camera follows the spy plane again; character select scrolls.'],
  ['e4149f1', 'CPUs buy planes and AA mounts too.'],
  ['38b4063', 'Zuihou, the Sengoku light carrier: she marks a spot and her squadron hovers over it, striking on her next turn. Her final weapon is the Kidō Butai.'],
  ['38b4063', 'Planes at every rarity (dive, torpedo, fighter, rocket wing, NXi heavy). Squads hover where anyone can shoot them; no flight deck means 30% softer.'],
  ['38b4063', 'AA mounts: point defence stops rockets and bombs, anti-air shoots planes and drones. Everyone gets a slot; Zuihou gets two.'],
  ['38b4063', 'Flak and rockets burst just short of drones and planes; flak throws its fragments at them.'],
  ['38b4063', 'A broken radio tower’s top flies off like a shell and crushes what it lands on.'],
  ['38b4063', 'S drops you off a bridge; switch weapons with Q, E or Tab. Laser drones climb half as high again.'],
  ['38b4063', 'CPUs think faster.'],
  ['05acb72', 'Hit popups add up: more hits on the same target raise its number instead of piling on, acid keeps one running total, and they stay up longer.'],
  ['dc274ed', 'Performance: still scenery and sprites are drawn once and reused, and CPUs think without stalling frames.'],
  ['6d8f7ef', 'The ring has depth: its far side rises behind it as a darker blocky silhouette.'],
  ['1c665e4', 'The ring in sections: city (a billion lights), radio masts, truss connectors and industry, grey blocks jutting in and out, towers above and below.'],
  ['58b9683', 'The ring rebuilt: a vast, shallow arc of blocky modules in rings within rings, trussed together, fogged by distance, beacons blinking along it.'],
  ['58b9683', 'When the Warm Meadows go cold, the flowers frost over and droop.'],
  ['73b26a3', 'The ring in the sky is a full lattice now: deck bays open to the sky, city lights, ribs and spires hanging off its underside.'],
  ['73b26a3', 'The lily meadow is now Warm Meadows, under the ring, kept warm by an old-world AHU. Destroy it and the snow comes.'],
  ['b1ce804', 'Three faces of Alstroemeria: AESR-U The Deck, AESR-L The Roots and ASTM-G The Ground, each with its own sky, scenery, giants and sudden death.'],
  ['b1ce804', 'Snowy Day is now The Far Territories, with the exo-surface ring across the sky.'],
  ['910ff14', 'Background life: radio towers and power lines on the ridges, and on Alstroemeria a skyrail with a blue and yellow train rocking by now and then.'],
  ['15cb8e6', 'Giants to hide under: a great pine, oak, dead tree or giant toadstool by map. Shoot the canopy away, or break the stem and the top crushes whoever is beneath.'],
  ['81cc56c', 'A spy plane sometimes crosses overhead and drops a golden crate: 70% repair, ¢1200 (+300 a round) or a 3-turn MAIA uplink.'],
  ['81cc56c', 'Weather fronts push twice as hard, and all of them (bar Rain) make shells hit harder; Force up to +80%.'],
  ['81cc56c', 'Kinetic damage is a percentage on the whole blast, up to +50%.'],
  ['81cc56c', 'Radio towers broken low swing over away from the blast and crush what they land on.'],
  ['7b6a3ba', 'Hostiles never hit each other; bomber drones toss bombs from up to 260 away; drone tanks sit on slopes; the FPV is a proper quad that pitches into its dive.'],
  ['7b6a3ba', 'One repair kit at a time; abilities cost half.'],
  ['7b6a3ba', 'Changelog lines carry the commit that made them.'],
  ['4b13dd9', 'The changelog gets its own tab.'],
  ['d51fbe5', 'Hostiles fire on every hostile turn. Several drones from round 2, and reinforcements grow in number and quality each cycle.'],
  ['d51fbe5', 'New hostiles: FPV kamikazes, carriers that airdrop drone tanks, drone tanks driving in from the map edge, and their final form, the Hatsuyuki android.'],
  ['d51fbe5', 'The NXi fleet fights overhead: from round 2, wreckage rains down as a round goes on.'],
  ['d51fbe5', 'MAIA repairs once a turn cycle, and stays down for two full cycles when shot out.'],
  ['d51fbe5', 'CPUs spread their fire instead of ganging up, drive out from under drones, and aim better at hostiles.'],
  ['d51fbe5', 'Leap (L): a long bound for 90% fuel, landing without fall damage.'],
  ['83bc3bf', 'Dying on your own turn passes it on. The Codex range resets when you die, and has a Reset range button.'],
  ['8c12300', 'G.W. Tiger: starter spread 1.5; Geschützwagen now halves the spread of every gun she fires.'],
  ['df87a8e', 'Help: How to play and About tabs, hints and a damage-number key.'],
  ['d34de47', 'Codex: no NaN for final weapons.'],
  ['2cce0ca', 'Neko Paradise (and every laser salvo) no longer stalls.'],
  ['f682a55', 'The target guide works for a mark behind you when the barrel is past vertical.'],
  ['d01d988', 'Touch: a MENU button; End turn moves into the pause menu.'],
  ['96e4a6f', 'NXi favicon and app icons.'],
  ['7190281', 'Touch: pinch to zoom.'],
  ['63b5a6f', 'Touch: arrow-key T pad, drag from your vehicle to aim, a landscape prompt. The view stretches to fit wide screens.'],
  ['f113960', 'Apollon: a bigger asteroid and crater, lava in bullet time, ground scorched beneath it.'],
  ['22ce20b', 'Morrighan: the sky tears open and black rockets rain out.'],
  ['2397303', 'Final weapons hit far harder; the NXi flagship\'s spinal lance.'],
  ['e0f77bb', 'Constellation: a mountain-sized MAIA behind the hills, and MAIA variants.'],
  ['df8a32e', 'Naito MAIA: a satellite built round one huge gun.'],
  ['4c42c98', 'G.W. battery: the Artillery II G.W. sprite and a Karl-Gerät on rails.'],
  ['dcbbbe4', 'Zero Point: the Naito MAIA fires from the Great Red Spot and deletes the ground.'],
  ['c5b1754', 'CPU names from the game\'s inspirations.'],
  ['d20377a', 'Final weapons (Ascendant), Ikaros, the NXi fleet strike.'],
  ['c2df1d7', 'Highways, radio towers, and structures that toughen through a match.'],
  ['b062c6f', 'Bridges break in sections.'],
  ['a965d5f', 'Laser drones and Arc Lance lightning.'],
  ['ed56ef2', 'Object 15X: KTS-T and a laser designator; seeded matches.'],
  ['f227a83', 'Bridges and power lines; seeking carpet bombs.'],
  ['5f92193', 'Jump, standable forts, quicker movement.'],
  ['bfc4d3f', 'The Codex: every character and gun with stats and analysis, and a test range.'],
  ['da76b0f', 'Guided rockets; Alban Eiler of Lymilark Future Sciences.'],
  ['6b71031', 'Hit popups by accuracy; CPUs that range in.'],
  ['4869750', 'Reloads, tiered firepower, a weapon rack, strong wind and character traits.'],
];
